version: '3'
services:

  docker-nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8081:8081
      - 8082:8082
    restart: always

  docker-ftp:
    build:
      context: ./ftp/
      dockerfile: Dockerfile
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: "someuser|Qwerty123!"
    restart: always

  docker-frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - docker-nginx

  docker-backend:
    build:
      context: ./backend/docholder/
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - docker-nginx
      - docker-postgres

  docker-postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
